const actionTypes = {
  LOAD_USERS: 'LOAD USERS',
  INSERT_USER: 'INSERT USER',
  UPDATE_USER: 'UPDATE USER',
  DELETE_USER: 'DELETE USER',
  LOAD_USER: 'LOAD USER',
  LOAD_DATA_CHALLENGE: 'LOAD DATA CHALLENGE',
  CREATE_CHALLENGE: 'CREATE CHALLENGE',
  UPDATE_CHALLENGE: 'UPDATE CHALLENGE',
};

export default actionTypes;
