const actionTypes = {
  LOAD_USERS: 'LOAD USERS',
  INSERT_USER: 'INSERT USER',
  UPDATE_USER: 'UPDATE USER',
  DELETE_USER: 'DELETE USER',
  LOAD_USER: 'LOAD USER',
  LOAD_TASKS_AND_REWARDS: 'LOAD TASKS AND REWARDS',
};

export default actionTypes;
